# Para Rollback 
name: AVD-VDI Lab Pipeline

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose script to run"
        required: true
        type: choice
        options:
          - create-avd
          - restart-avd
          - remove-avd
          - create-vdi
          - restart-vdi
          - remove-vdi

      vmName:
        description: "Machine name"
        required: true

      pool:
        description: "Pool / HostPool name"
        required: true

jobs:

  validate:
    runs-on: windows-latest

    steps:
      - name: Show Parameters
        shell: pwsh
        run: |
          Write-Host "VM:" "${{ github.event.inputs.vmName }}"
          Write-Host "Pool:" "${{ github.event.inputs.pool }}"
          Write-Host "Action:" "${{ github.event.inputs.action }}"

  approve:
    needs: validate
    runs-on: windows-latest
    environment:
      name: manual-approval

    steps:
      - run: echo "Waiting approval..."

  execute:
    needs: approve
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Script
        shell: pwsh
        run: |
          $action = "${{ github.event.inputs.action }}"

          switch ($action) {

            "create-avd" { ./scripts/create-VM-AVD.ps1 }
            "restart-avd" { ./scripts/reiniciar-VM-AVD.ps1 }
            "remove-avd" { ./scripts/remover-VM-AVD.ps1 }

            "create-vdi" { ./scripts/create-VM-VDI.ps1 }
            "restart-vdi" { ./scripts/reiniciar-VM-VDI.ps1 }
            "remove-vdi" { ./scripts/remover-VM-VDI.ps1 }
          }
